- name: Install and configure Jenkins
  hosts: all
  become: true
  
  vars:
    jenkins_admin_username: admin
    jenkins_admin_password: Password
    jenkins_plugin_name: some-plugin-name
  
  tasks:
    
    - name: Update apt cache
      apt:
        update_cache: yes
      become: true
      
    - name: Install Jenkins
      apt:
        name: openjdk-11-jdk
        state: present
      become: true

    - name: Add Jenkins apt key and repository with shell commands
      shell: |
        sudo mkdir -p /usr/share/keyrings/
        sudo curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
        sudo echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
        sudo apt update
      become: true
    
    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      become: true

    - name: Install Jenkins plugin
      jenkins_plugin:
        name: "{{ jenkins_plugin_name }}"
        state: present
        url_username: "{{ jenkins_admin_username }}"
        url_password: "{{ jenkins_admin_password }}"
        url: "http://localhost:8080"
      become: true

    - name: Create Jenkins admin user
      jenkins_script:
        url: "http://localhost:8080"
        user: "{{ jenkins_admin_username }}"
        password: "{{ jenkins_admin_password }}"
        script: |
          import jenkins.model.*
          import hudson.security.*
          import org.jenkinsci.plugins.*

          def instance = Jenkins.getInstance()

          def hudsonRealm = new HudsonPrivateSecurityRealm(false)
          instance.setSecurityRealm(hudsonRealm)

          def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
          instance.setAuthorizationStrategy(strategy)

          instance.save()

          def user = hudsonRealm.createAccount('{{ jenkins_admin_username }}', '{{ jenkins_admin_password }}')
          user.save()
      become: true

